### ISSUE TITLE
Teller import fails with YNAB::ApiErrror

### ISSUE THREAD

**Issue by kot-behemoth** [fintech-to-ynab/fintech-to-ynab#100]
Just tried running Teller import for Nationwide for the first time, following the most [recent Wiki page](https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/Import:-Teller).

However, the entire process fails with:

```
bash-3.2$ 
./bin/import teller --token xxx --ynab_account_id xx
bash-3.2$ [0] XXX

Account ID: 0
I, [2018-08-18T15:21:34.342705 #44763]  INFO -- : Splitting 109 transactions into 6 batches
I, [2018-08-18T15:21:34.342805 #44763]  INFO -- : Processing batch 1 of 6
D, [2018-08-18T15:21:34.346392 #44763] DEBUG -- : ETHON: Libcurl initialized
D, [2018-08-18T15:21:34.927722 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets response_code=200 return_code=ok total_time=0.580277
D, [2018-08-18T15:21:35.124352 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.18529399999999996
E, [2018-08-18T15:21:35.124796 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:35.124891 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:35.192834 #44763]  INFO -- : false
I, [2018-08-18T15:21:35.192915 #44763]  INFO -- : Processing batch 2 of 6
D, [2018-08-18T15:21:35.379748 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.18225
E, [2018-08-18T15:21:35.380175 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:35.380212 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:35.450374 #44763]  INFO -- : false
I, [2018-08-18T15:21:35.450485 #44763]  INFO -- : Processing batch 3 of 6
D, [2018-08-18T15:21:35.618276 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.164834
E, [2018-08-18T15:21:35.618901 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:35.618953 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:35.690904 #44763]  INFO -- : false
I, [2018-08-18T15:21:35.690982 #44763]  INFO -- : Processing batch 4 of 6
D, [2018-08-18T15:21:35.869504 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.173541
E, [2018-08-18T15:21:35.869987 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:35.870017 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:35.946354 #44763]  INFO -- : false
I, [2018-08-18T15:21:35.946435 #44763]  INFO -- : Processing batch 5 of 6
D, [2018-08-18T15:21:36.119871 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.169616
E, [2018-08-18T15:21:36.120824 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:36.120897 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:36.193545 #44763]  INFO -- : false
I, [2018-08-18T15:21:36.193650 #44763]  INFO -- : Processing batch 6 of 6
D, [2018-08-18T15:21:36.360169 #44763] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/XXX/transactions/bulk response_code=500 return_code=ok total_time=0.163735
E, [2018-08-18T15:21:36.360860 #44763] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T15:21:36.360905 #44763] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:45:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T15:21:36.436025 #44763]  INFO -- : false
```

Is this a known issue? Thanks!

**Comment by scottrobertson** [comment]
Very helpful of ynab to just return a 500 error. 

Let me add some better logging and try and work out the issue here.

**Comment by scottrobertson** [comment]
@kot-behemoth I have pushed some more logging. Please update and run it again.

I have not used Teller in a long time, as Barclays has been out of action. So perhaps something has changed. This should let us know though.

**Comment by scottrobertson** [comment]
Hmm, so i just ran this across my old nationwide account, and it worked just fine. Let me see them logs when you can.

**Comment by kot-behemoth** [comment]
Interesting - could be me using a wrong id or something. Here's a snippet with the new logging

```
I, [2018-08-18T16:56:14.542710 #45038]  INFO -- : Splitting 109 transactions into 6 batches
I, [2018-08-18T16:56:14.542811 #45038]  INFO -- : Processing batch 1 of 6
D, [2018-08-18T16:56:14.545896 #45038] DEBUG -- : ETHON: Libcurl initialized
D, [2018-08-18T16:56:15.126037 #45038] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets response_code=200 return_code=ok total_time=0.57919
D, [2018-08-18T16:56:15.369591 #45038] DEBUG -- : ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/d57000af-9598-4a04-9d54-7dce67512703/transactions/bulk response_code=500 return_code=ok total_time=0.231826
E, [2018-08-18T16:56:15.370427 #45038] ERROR -- : YNAB::Client.create_transactions failure
E, [2018-08-18T16:56:15.370980 #45038] ERROR -- : YNAB::Client.create_transactions Request Body: [{:import_id=>"Tae08e1fe-ec52-425a-a464-93437ac0...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-43450, :memo=>"xxx", :date=>Sat, 18 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T658df6e8-532b-402e-9b21-5835e580...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-17980, :memo=>"xxx", :date=>Sat, 18 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T99177a29-9e07-479b-ad57-0f062204...", :account_id=>"sss", :payee_name=>"xxx", :amount=>-4500, :memo=>"xxx", :date=>Sat, 18 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Td2ab5325-f9ef-48df-9a1d-da1258e4...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-4090, :memo=>"xxx", :date=>Sat, 18 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Tcc104389-3a3b-4b96-83cb-6b4003d1...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-1100, :memo=>"xxx", :date=>Sat, 18 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Tef80b64d-3ea8-4ee9-ae6f-3063383d...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-100000, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T82c33da6-3a63-4fcb-aec7-64efb47a...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-15300, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T161f3cdb-ba66-4292-8283-af1a58d5...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-14040, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T22e841a3-68e8-4c12-9106-ea27f523...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-9500, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T3ebd9a1b-dbe1-457b-94d1-77d13422...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-6800, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T95576896-f3be-4cd8-8a2c-118c59d1...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-3250, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T8f969baa-5349-42bb-a9d0-78a0fd03...", :account_id=>"xxx", :payee_name=>"xxc", :amount=>-2990, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T276d2b50-c666-48ad-ab7c-44436938...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-2600, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Tbed948b7-1642-44de-bf62-04ad5ca4...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>2100000, :memo=>"xxx", :date=>Fri, 17 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T3211a9d5-99fd-4329-a346-4730eaf1...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-13970, :memo=>"xxx", :date=>Thu, 16 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T99939ed7-91d6-4201-a7f8-e9f2496e...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-3000, :memo=>"xxx", :date=>Thu, 16 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Te13876a3-d87e-44cb-8551-af920b2a...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>21060, :memo=>"xxx", :date=>Thu, 16 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T2a55a662-d995-4f8e-9fde-e9d119c5...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-20980, :memo=>"xxx", :date=>Wed, 15 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"T3792e8db-d8cd-4269-a818-1017482a...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-19500, :memo=>"xxx", :date=>Wed, 15 Aug 2018, :cleared=>"Uncleared", :flag=>nil}, {:import_id=>"Tdc3bc62f-dc6d-4810-b875-f727a7c7...", :account_id=>"xxx", :payee_name=>"xxx", :amount=>-12940, :memo=>"xxx", :date=>Wed, 15 Aug 2018, :cleared=>"Uncleared", :flag=>nil}]
E, [2018-08-18T16:56:15.943696 #45038] ERROR -- : YNAB::Client.create_transactions Response: {"error":{"id":"500","name":"internal_server_error","detail":"An unexpected error has occurred"}}
E, [2018-08-18T16:56:15.943763 #45038] ERROR -- : Internal Server Error (YNAB::ApiError)
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api_client.rb:68:in `call_api'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/lib/ruby/gems/2.5.0/gems/ynab-1.3.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/client.rb:46:in `create_transactions'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:38:in `block in create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `each_slice'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `with_index'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/ynab/bulk_transaction_creator.rb:20:in `create'
/Users/greg/Dropbox/projects/fintech-to-ynab/app/services/import/teller.rb:22:in `import'
./bin/import:72:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:71:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/import.rb:5:in `block in <top (required)>'
I, [2018-08-18T16:56:16.110565 #45038]  INFO -- : false
```

**Comment by kot-behemoth** [comment]
I decided to check my setup (once I realised that pretty much all the docs have been updated) — and, after updating some of the .env variables, it's all working as expected. Apologies for raising the issue — this was totally my error!

**Comment by scottrobertson** [comment]
Awesome, thanks 👍
