### ISSUE TITLE
Revolut for Business

### ISSUE THREAD

**Issue by minolim** [fintech-to-ynab/fintech-to-ynab#113]
Hi there,

Full disclosure: I can query my revolut for business account with requests on python, so I know that token is working.

I am running the console comand on heroku to upload to ynab,

The result I get is : error: 404 Not Found. Use --trace to view backtrace

Any idea?

**Comment by scottrobertson** [comment]
@minolim can you run it with `--trace` please

**Comment by minolim** [comment]
```
W
        12: from ./bin/import:75:in `block (2 levels) in <main>'
        11: from /app/app/services/import/revolut_business.rb:13:in `import'
        10: from /app/app/services/import/revolut_business.rb:30:in `transactions'
         9: from /app/app/services/import/revolut_business.rb:38:in `get'
         8: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
         7: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
         6: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
         5: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
         4: from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
         3: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
         2: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
         1: from /app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 404 Not Found (RestClient::NotFound)

```

**Comment by scottrobertson** [comment]
Thanks.

It's hard for me to test this now as i closed my Revolut account.

**Comment by minolim** [comment]
Let me know if I can help somehow - I code in python, but have no clue about ruby

**Comment by scottrobertson** [comment]
@minolim can you email me at scottymeuk @ gmail. I no longer have a Revolut for Business account, and need your help testing this if possible.
