### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by n0k5** [fintech-to-ynab/fintech-to-ynab#59]
I've set this up with Monzo -> YNAB to the best of my ability, using the Monzo and YNAB API respectively. I've set my `YNAB_ACCESS_TOKEN` and my `YNAB_ACCOUNT_ID` in the config vars, running on Heroku. It seems to be all set up correctly, but when I spend on my Monzo card nothing actually gets pushed to my YNAB account.

Am I missing something? Is there something I could share to help troubleshoot this? I've looked at the logs, but nothing other than `bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)` seems to look off to me. This error only fired once this morning when I started up the script.

**Comment by scottrobertson** [comment]
Hey

- Could you paste the logs in here?
- Did you setup the Monzo webhook?
- Do you an old prepaid account, or just a current account?

**Comment by n0k5** [comment]
No problem:

```
2018-04-03T09:41:02.198146+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/launcher.rb:397:in `block in setup_signals'
2018-04-03T09:41:02.198153+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/single.rb:106:in `run'
2018-04-03T09:41:02.198143+00:00 app[web.1]: SignalException: SIGTERM
2018-04-03T09:41:02.198154+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
2018-04-03T09:41:02.198158+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
2018-04-03T09:41:02.198151+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/single.rb:106:in `join'
2018-04-03T09:41:02.198160+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/puma:22:in `load'
2018-04-03T09:41:02.197977+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)
2018-04-03T09:41:02.198156+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
2018-04-03T09:41:02.198185+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/puma:22:in `<top (required)>'
```

The [Monzo webhook](https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/import:-Monzo#webhooks) has been setup. I just checked it again to confirm, and listing the webhooks brings it up with the correct URL (including /monzo at the end).

I'm using the newer current account after recently (a week ago+) upgrading.

**Comment by scottrobertson** [comment]
And webhook is using the correct account t_id? There will be 2. You need the uk_retail one.

**Comment by n0k5** [comment]
Ahh — this might be the issue. I remember leaving the `account_id` as `"account_id": "$account_id",` instead of manually changing it. I just checked and the one registered on the webhook is the wrong account... 🤦🏻‍♂️

I've updated the webhook on Monzo now. Is there a way of testing to see if it's working, or do I just need to spend on my card and see if it comes through?

**Comment by n0k5** [comment]
@ganey that worked, thanks.

I can confirm this is working now. My problem was the Monzo account ID defaulted to my closed account rather than my open one but wasn't immediately obvious. The solution was to list my accounts on the Monzo API, and grab the account ID from there instead.

**Comment by scottrobertson** [comment]
Awesome! Added a note to the wiki too https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/Import:-Monzo
