### ISSUE TITLE
YNAB API error importing Monzo Transactions

### ISSUE THREAD

**Issue by jakehall-IW** [fintech-to-ynab/fintech-to-ynab#87]
Just tried to import my Monzo transactions into YNAB, but I'm getting the following error (running this code inside the Heroku dyno). I've double checked the secrets and IDs and they all seem to be correct. Have you got any pointers for this please?

```
irb(main):004:0> Import::Monzo.new("xxx", "xxx", "xxx").import
Splitting 2075 transactions into 104 batches
Processing batch 1 of 104
ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/xxx/transactions/bulk response_code=400 return_code=ok total_time=0.477553
YNAB::ApiError: Bad Request
	from app/services/ynab/client.rb:42:in `create_transactions'
	from app/services/ynab/bulk_transaction_creator.rb:39:in `block in create'
	from app/services/ynab/bulk_transaction_creator.rb:21:in `each'
	from app/services/ynab/bulk_transaction_creator.rb:21:in `each_slice'
	from app/services/ynab/bulk_transaction_creator.rb:21:in `with_index'
	from app/services/ynab/bulk_transaction_creator.rb:21:in `create'
	from app/services/import/monzo.rb:49:in `import'
	from (irb):4
```

Thanks!

**Comment by scottrobertson** [comment]
Hey

Can you run the following:

```
begin
  Import::Monzo.new("xxx", "xxx", "xxx").import
rescue => e 
  raise e.response_body.to_yaml
end
```

Still quite a bit of work to do to make errors more clear. But this should give us an idea of what is wrong.

**Comment by jakehall-IW** [comment]
Thanks for the tip! This is the error:

```
RuntimeError: --- '{"error":{"id":"400","name":"bad_request","detail":"{\"transactions\":[{\"index\":5,\"error\":{\"payee_name\":[\"is
  too long (maximum is 50 characters)\"]}}]}"}}'
```
